-- CreateTable bot_chain_locks: per-chain send lease for the shared bot key.
-- One row per chain, created on demand by the first send. `holder` is an opaque
-- token generated by the acquirer so a release can never free someone else's
-- lease; `expires_at` bounds a lease whose holder died mid-send.
-- `last_nonce` is the durable ledger that makes nonce selection independent of a
-- load-balanced RPC's pending view.
CREATE TABLE IF NOT EXISTS "bot_chain_locks" (
  "chain_id"      INTEGER PRIMARY KEY,
  "holder"        VARCHAR(64),
  "acquired_at"   TIMESTAMPTZ,
  "expires_at"    TIMESTAMPTZ,
  "last_nonce"    BIGINT,
  "last_nonce_at" TIMESTAMPTZ
);
